In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
from shapely import wkt

In [24]:
access_df = pd.read_csv("/Users/feliphlvo/Documents/Minerva/Capstone/data/local/access_df.csv",index_col=0)
access_df = gpd.GeoDataFrame(access_df, geometry = access_df["geometry"].apply(wkt.loads), crs = "EPSG:5641")

/Users/feliphlvo/opt/anaconda3/envs/cap_env/lib/python3.10/site-packages/geopandas/array.py:93: ShapelyDeprecationWarning:

__len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.

In [25]:
access_df = access_df.to_crs(epsg=4326)

/Users/feliphlvo/opt/anaconda3/envs/cap_env/lib/python3.10/site-packages/geopandas/array.py:93: ShapelyDeprecationWarning:

__len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.

In [27]:
access_df.head()

,state,n_households,n_people,avg_monthly_earnings,n_people_15to17_white,n_people_15to17_black,n_people_15to17_asian,n_people_15to17_parda,n_people_15to17_indigenous,n_people_15,...,geometry,microregion_id,microregion_name,mesoregion_id,mesoregion_name,n_people_15to17acc,e2sfca_n_classes,e2sfca_n_teachers,3sfca_n_classes,3sfca_n_teachers
sector_id,,,,,,,,,,,,,,,,,,,,,
170025105000002,TO,115.0,300.0,648.06,1.0,0.0,0.0,10.0,0.0,6.0,...,"POLYGON ((-49.14747 -9.57424, -49.14425 -9.576...",17003.0,Miracema do Tocantins,1701.0,Ocidental do Tocantins,11.0,0.156540,0.334205,0.156540,0.334205
170030105000001,TO,286.0,1123.0,927.45,10.0,2.0,3.0,59.0,0.0,26.0,...,"POLYGON ((-47.48000 -6.56078, -47.45877 -6.547...",17001.0,Bico do Papagaio,1701.0,Ocidental do Tocantins,74.0,1.858669,0.272249,1.963982,0.038130
170030105000002,TO,294.0,1101.0,478.33,11.0,0.0,1.0,46.0,0.0,23.0,...,"POLYGON ((-47.46688 -6.56653, -47.46468 -6.566...",17001.0,Bico do Papagaio,1701.0,Ocidental do Tocantins,58.0,1.888139,0.310532,1.951083,0.048693
170030105000003,TO,102.0,385.0,453.32,3.0,1.0,0.0,17.0,0.0,8.0,...,"POLYGON ((-47.46737 -6.53921, -47.46668 -6.539...",17001.0,Bico do Papagaio,1701.0,Ocidental do Tocantins,21.0,0.349708,0.044056,0.369478,0.005189
170030105000004,TO,56.0,245.0,368.55,3.0,0.0,0.0,11.0,0.0,6.0,...,"POLYGON ((-47.50399 -6.56052, -47.50016 -6.563...",17001.0,Bico do Papagaio,1701.0,Ocidental do Tocantins,14.0,2.043338,0.823609,1.619455,0.304899

In [34]:
subset_df = access_df[access_df["city_name"] == "SÃ£o Paulo"]
str_json = subset_df[["geometry", "city_name"]].to_json()

In [28]:
subset_df.head()

,state,n_households,n_people,avg_monthly_earnings,n_people_15to17_white,n_people_15to17_black,n_people_15to17_asian,n_people_15to17_parda,n_people_15to17_indigenous,n_people_15,...,geometry,microregion_id,microregion_name,mesoregion_id,mesoregion_name,n_people_15to17acc,e2sfca_n_classes,e2sfca_n_teachers,3sfca_n_classes,3sfca_n_teachers
sector_id,,,,,,,,,,,,,,,,,,,,,
130260305000002,AM,107.0,414.0,586.61,10.0,1.0,1.0,17.0,0.0,11.0,...,"POLYGON ((-60.02330 -2.94981, -60.02195 -2.948...",13007.0,Manaus,1303.0,Centro Amazonense,29.0,0.319465,0.651613,0.953049,1.972381
130260305000004,AM,180.0,664.0,595.22,8.0,3.0,1.0,18.0,3.0,15.0,...,"POLYGON ((-60.02794 -2.94733, -60.03186 -2.947...",13007.0,Manaus,1303.0,Centro Amazonense,33.0,0.359199,0.732451,0.995545,2.064985
130260305000005,AM,160.0,678.0,753.98,13.0,8.0,0.0,30.0,2.0,17.0,...,"POLYGON ((-60.03357 -2.94814, -60.03186 -2.947...",13007.0,Manaus,1303.0,Centro Amazonense,53.0,0.343158,0.700090,0.977961,2.027284
130260305000007,AM,110.0,450.0,582.86,7.0,1.0,0.0,24.0,0.0,10.0,...,"POLYGON ((-59.98376 -2.91508, -59.98379 -2.914...",13007.0,Manaus,1303.0,Centro Amazonense,32.0,0.377522,0.752613,1.066391,2.168926
130260305000010,AM,61.0,237.0,416.16,15.0,0.0,0.0,13.0,0.0,3.0,...,"POLYGON ((-59.80316 -3.07215, -59.79770 -3.070...",13007.0,Manaus,1303.0,Centro Amazonense,28.0,0.006109,0.014906,0.227283,0.554557

In [36]:
fig = px.choropleth_mapbox(access_df, geojson=access_df, locations=access_df.index, color="3sfca_n_classes",
                           mapbox_style="open-street-map", opacity=0.5, center={"lat": -23.5558, "lon":-46.6396}, zoom=9.5,
                           hover_data=["city_name"])
fig.show()